### ISSUE TITLE
[FEATURE]: One-Step Image Retrieval Docker Image

### ISSUE THREAD

**Issue by soulteary** [milvus-io/bootcamp#1086]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Is your feature request related to a problem? Please describe.

The current demo is a bit complicated and depends on many components.

Perhaps there should be an easy way for users to start with one click and experience the magic of vector retrieval technology.

### Describe the solution you'd like

It only needs one command, a relatively small image, and a relatively simple organizational structure, which is more suitable for running locally than a simulated production structure.

### Task

- [x] small front-end (client-side) 
  - [x] https://github.com/milvus-io/bootcamp/pull/1081
  - [x]  https://github.com/milvus-io/bootcamp/pull/1098
  - [x] https://github.com/milvus-io/bootcamp/pull/1100
  - [x] https://github.com/milvus-io/bootcamp/pull/1101
- [x] small base image (milvus + sdk) 
  - [x] https://github.com/milvus-io/bootcamp/pull/1082
- [x] small server image (towhee + python deps) 
  - [x] https://github.com/milvus-io/bootcamp/pull/1083
  - [x] https://github.com/milvus-io/bootcamp/pull/1097
  - [x] https://github.com/milvus-io/bootcamp/pull/1096
  - [x] https://github.com/milvus-io/bootcamp/pull/1088
- [x] final docker image
  - [x]  https://github.com/milvus-io/bootcamp/pull/1084
  - [x]  https://github.com/milvus-io/bootcamp/pull/1085
  - [x]  https://github.com/milvus-io/bootcamp/pull/1090
  - [x] https://github.com/milvus-io/bootcamp/pull/1099
  - [x] https://github.com/milvus-io/bootcamp/pull/1101
  - [x] https://github.com/milvus-io/bootcamp/pull/1102
